server.port=8083

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/logistics_analytics

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Actuator / Prometheus
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always

# OpenTelemetry / Jaeger
management.tracing.sampling.probability=1.0
otel.exporter.otlp.endpoint=http://localhost:4318
